"""Content-oriented file cataloging."""

from .catalog import Catalog
from .errors import InvalidCatalogError, RefreshFailure, ScanFailure, StaleRefreshError, TaggingError
from .models import (
    ContentId,
    ContentTagAssertion,
    ContentTagView,
    CurrentFileSearch,
    CurrentFileSort,
    CurrentFileTagView,
    DuplicateGroupSearch,
    DuplicateGroupView,
    DuplicateSummary,
    FileObservation,
    HistoricalObservation,
    Location,
    MultiTagContentSearch,
    RefreshChange,
    RefreshChangeKind,
    RefreshChangeSet,
    RefreshSummary,
    ScanProgress,
    ScanRun,
    ScanSummary,
    TagAwareCurrentFileSearch,
    TaggedContent,
    TaggedContentSearch,
    TagMatchMode,
    TagProvenance,
    TagProvenanceKind,
    validate_tag_name,
)

__all__ = [
    "Catalog",
    "ContentId",
    "ContentTagAssertion",
    "ContentTagView",
    "CurrentFileSearch",
    "CurrentFileSort",
    "CurrentFileTagView",
    "DuplicateGroupSearch",
    "DuplicateGroupView",
    "DuplicateSummary",
    "FileObservation",
    "HistoricalObservation",
    "InvalidCatalogError",
    "Location",
    "MultiTagContentSearch",
    "RefreshChange",
    "RefreshChangeKind",
    "RefreshChangeSet",
    "RefreshFailure",
    "RefreshSummary",
    "StaleRefreshError",
    "ScanFailure",
    "ScanProgress",
    "ScanRun",
    "ScanSummary",
    "TaggedContent",
    "TaggedContentSearch",
    "TagAwareCurrentFileSearch",
    "TagMatchMode",
    "TaggingError",
    "TagProvenance",
    "TagProvenanceKind",
    "validate_tag_name",
]
